### ISSUE TITLE
Detail how to interact with visualizations of Prometheus

### ISSUE THREAD

**Issue by stsievert** [perdy/starlette-prometheus#12]
I'm a new user to Starlette, and looking to monitor some Gunicorn processes for my Starlette server. This library looks promising, and I've successfully integrated and viewed the plain text stats at `/metrics`.

However, I'd like a better visualization of these performance metrics. I've looked at integrating Grafana, but am having difficulty (https://prometheus.io/docs/visualization/grafana/ looks promising).

I'm looking for the most basic level of monitoring; the console templates at https://prometheus.io/docs/visualization/consoles/ look promising.

It'd be really nice to have the following:

* A couple sentences describing the configuration that Grafana needs to use starlette-prometheus (which I suspect is just prometheus).
* Basic integration with visualizations. I'd like to see some basics graphs of the stats at `/metrics` with a simple HTML page. I think I'd like to see an interface like this:

``` python
from starlette.applications import Starlette
from starlette_prometheus import metrics, metric_viz, PrometheusMiddleware

app = Starlette()
app.add_middleware(PrometheusMiddleware)
app.add_route("/metrics/", metrics)
app.add_route("/metric-viz/", metric_viz)
```

**Comment by streaming-pete-zz** [comment]
use grafana. it is very simple to setup with prometheus.
You will need to setup a prometheus server to scrape your servers at /metrics over time and then use grafana to query the prometheus server. You can't really use the metrics page as a one off monitoring tool as its all time based statistics

**Comment by stsievert** [comment]
Thanks. I've got it working now. I'm closing this issue. I found it most useful to use the exposed API. I used the [their Docker container][1] to start up Prometheus, then used their [sample config][2]. The only part I changed in their sample config:

``` diff
-      - targets: ['localhost:9090']
+      - targets: ['server:8201']

```

Here's the relevant portion of my `docker-compose.yml`:

``` yaml
  server:
    ...
    ports:
      - "8421:8421"
    expose:
      - 8421

  prom:
    image: prom/prometheus
    expose:
      - 9090
    volumes:
      - ./config:/etc/prometheus  # config has file prometheus.yml
```

I got Grafana up and running (again with Docker), but I found it to be not suitable for the visualization I wanted.

[1]:https://prometheus.io/docs/prometheus/latest/installation/#using-docker
[2]:https://prometheus.io/docs/introduction/first_steps/#configuring-prometheus

**Comment by trallnag** [comment]
@stsievert, do you mind sharing what you miss in Grafana? And you forgot to close the issue

**Comment by stsievert** [comment]
I wanted to specify some very specific plots. Grafna didn't have enough customization to let that happen easily.
