### ISSUE TITLE
How to add a custom metric?

### ISSUE THREAD

**Issue by streaming-pete-zz** [perdy/starlette-prometheus#14]
Is there provision in this plugin to add a custom metric? We are using FastAPI to host a custom application, I need the ability to add a custom metric.

Any info on how to do this would be good.

Thanks

**Comment by perdy** [comment]
Hello!

The scope of this project is to provide a middleware for Starlette and its frameworks ([FastAPI](https://github.com/tiangolo/fastapi), [Flama](https://github.com/perdy/flama), [Responder](https://github.com/taoufik07/responder)). This middleware contains a set of predefined metrics related to http requests/responses.

In case you want to add a custom metric you should add it using [Prometheus Client](https://github.com/prometheus/client_python). You can find some examples in their repo.
