### ISSUE TITLE
Consider bumping requirement versions

### ISSUE THREAD

**Issue by sebastienvercammen** [perdy/starlette-prometheus#17]
Hi, there.

In short, I created a new project over the weekend and started using the latest `prometheus_client==0.8.0`. After also adding `starlette-prometheus`, there's a version conflict:

> ERROR: starlette-prometheus 0.7.0 has requirement prometheus_client<0.8,>=0.7, but you'll have prometheus-client 0.8.0 which is incompatible.

Can you consider bumping requirement versions so we can use the latest versions?

**Comment by perdy** [comment]
Closed by #18
