### ISSUE TITLE
Releasing new version with updated prometheus-client dep?

### ISSUE THREAD

**Issue by DMantis** [perdy/starlette-prometheus#24]
Hello! I have a deps conflict due to the fact that current version fron pypi 0.7.0 is still list prometheus-client dep as <8.0 in poetry, but another package needs prometheus-client >=8.0. 
I see that updated dependency is already merged since august, is it possible to release something like v0.7.1 with this dependency?

**Comment by Samreay** [comment]
@perdy any chance for a new release?

**Comment by perdy** [comment]
Of course, I'll release a new version asap.

**Comment by tux21b** [comment]
Any updates yet? I am also interested in an updated prometheus-client dependency.

**Comment by perdy** [comment]
Released a new version with prometheus-client dependency updated to 0.11.
