### ISSUE TITLE
Is this project no longer maintained?

### ISSUE THREAD

**Issue by PyDataBlog** [perdy/starlette-prometheus#46]
It seems all the PRs are stuck and issues not even acknowledged. @perdy

**Comment by perdy** [comment]
Hi @PyDataBlog,

I appreciate your patience and understanding. At the moment, my primary focus is directed towards other projects, particularly [Flama](https://flama.dev/), demanding the majority of my time and attention. This has unfortunately led to delays in addressing pull requests and issues for this project.

I want to assure you that I value your contributions and the issues raised. Although my availability is limited, I will make an effort to periodically check and address matters related to this project to ensure its continued maintenance and improvement.

**Comment by PyDataBlog** [comment]
I could help maintain this one if you want?
