### ISSUE TITLE
[FEATURE] Path template instead of actual path in metrics

### ISSUE THREAD

**Issue by unmade** [perdy/starlette-prometheus#5]
Hi, there!

Thanks for a great middleware! I've been using it a while and now I want to show response time by url in grafana. It works good with regular paths, like `/users`, but not with templated paths like `/users/{id}` because in `/metrics` they appear as actual paths (`/users/1`, `/users/2`, etc...)

I've made a quick pull request https://github.com/perdy/starlette-prometheus/pull/6 for this. Let me know what you think of this idea and feel free to decline it if anything

**Comment by perdy** [comment]
Thanks !

It's a nice improvement and I'd like to get it merged. Your implementation in #6 is fair but I'd prefer to avoid losing info from captured requests of a single resource object (`/users/{id}/`) so, it would be nice to use the template as the `path` label value, but we could extract the id and put it as a new label. Does it sound reasonable?

**Comment by unmade** [comment]
Yes, that's totally reasonable. Maybe we should even keep all current labels as is (to not break anything) and instead add another label like `path_tpl`?

**Comment by dedsm** [comment]
Hello! it seems the release was not published in pypi :(

**Comment by dedsm** [comment]
also @perdy I stumbled upon an issue with the actual path being included in the series, if you have many different paths (like say you have thousands of users and have /users/{user_id}/ in the path), prometheus cardinality goes through the roof, with `prometheus_tsdb_head_series` growing very fast, wouldn't it be better to just remove the actual path and keep the template?
