### ISSUE TITLE
New Pypi release

### ISSUE THREAD

**Issue by JoseKilo** [perdy/starlette-prometheus#50]
Hi, nice project, thank you for maintaining it !

Looks like there is a new 0.10.0 release committed: https://github.com/perdy/starlette-prometheus/commit/3d2f82e136116c78c66db653b6f6a0b262ad6d89

But it isn't tagged (https://github.com/perdy/starlette-prometheus/tags)
And it hasn't been published to Pypi: https://pypi.org/project/starlette-prometheus/#history

I'm interested in getting this issue solved in particular: https://github.com/perdy/starlette-prometheus/issues/44#issuecomment-1927076805

The commit is more than 3 months old now, is there anything blocking the release ?

**Comment by c0deaddict** [comment]
I'm also waiting on this. Could you please release 0.10.0 on PyPi @perdy :pray:

**Comment by perdy** [comment]
Version 0.10.0 is now published and available in PyPI.
