### ISSUE TITLE
the path label makes prometheus cardinality grow too big

### ISSUE THREAD

**Issue by dedsm** [perdy/starlette-prometheus#7]
as mentioned in https://github.com/perdy/starlette-prometheus/issues/5#issuecomment-554773428 by keeping the `path` in the metric labels, there's a potential to have a very high cardinality if a project has many different paths, going against the Prometheus best practices https://prometheus.io/docs/practices/instrumentation/#do-not-overuse-labels.

I propose removing the path from the labels or at least make it configurable.

Cheers

**Comment by perdy** [comment]
Yeah, that was my main concern with #5 so keeping only the path templates sounds like a proper solution now.

Thanks !
